version: '3.8'

services:

  consumer:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
      - rabbitmq
    environment:
      POSTGRES_DB: "parameters"
      POSTGRES_HOST: "pghost"
      POSTGRES_USER: "user_name"
      POSTGRES_PASSWORD: "user_password"
      RABBITMQ_HOST: "rabbitmq"

  rabbitmq:
    image: rabbitmq:3.10.23-management
    container_name: rabbitmq3-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres
    ports:
      - "5432:5432"
    hostname: pghost
    environment:
      POSTGRES_DB: "parameters"
      POSTGRES_HOST: "pghost"
      POSTGRES_USER: "user_name"
      POSTGRES_PASSWORD: "user_password"
