apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: consumer
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8000
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: heureka-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: heureka-config
                  key: POSTGRES_HOST
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: heureka-config
                  key: RABBITMQ_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: heureka-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heureka-secret
                  key: POSTGRES_PASSWORD
