apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: consumer
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
