apiVersion: v1
kind: Secret
metadata:
  name: heureka-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.credentials.postgresPassword }}
  RABBITMQ_DEFAULT_USER: {{ .Values.credentials.rabbitmqUser }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.credentials.rabbitmqPassword }}
